// 002 Even Fibonacci Numbers
// https://projecteuler.net/problem=2
//
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the 
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1,2,3,5,8,13,21,34,55,89,...
// By considering the terms in the Fibonacci sequence whose values
// do not exceed four million, find the sum of the even-valued terms.

int sumOfAllEvenFibonaccis = 2;
int lastFibo = 2;
int currentFibo = 3;

for ( int i = 1;currentFibo < 4000000; i++)
{
    if(i > 2 && i == lastFibo + currentFibo)
    {
        lastFibo = currentFibo;
        currentFibo = i;

        if (currentFibo % 2 == 0)
        {
            sumOfAllEvenFibonaccis += currentFibo;
        }
    }
}
Console.WriteLine("---------------------");
Console.WriteLine(sumOfAllEvenFibonaccis);